# Generated by Django 3.1 on 2020-08-24 19:41

from django.db import migrations, models
import localflavor.us.forms


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200824_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='SSN',
            field=models.CharField(default=-4099, max_length=11, validators=[localflavor.us.forms.USSocialSecurityNumberField.clean]),
            preserve_default=False,
        ),
    ]
